# fly.toml app configuration file generated for sendnotes-wandering-pond-3212 on 2024-12-01T19:06:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sendnotes-wandering-pond-3212'
primary_region = 'ams'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = 'production'
  DB_CONNECTION = "pgsql"
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  APP_URL = "https://sendnotes-wandering-pond-3212.fly.dev/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1024'
  cpu_kind = 'shared'
  cpus = 1
